package jinres

type StatusCode interface {
	// 1xx Informational
	Continue()
	SwitchingProtocols()
	Processing()
	EarlyHints()
	// 2xx Success
	OK()
	Created()
	Accepted()
	NonAuthoritativeInformation()
	NoContent()
	ResetContent()
	PartialContent()
	MultiStatus()
	AlreadyReported()
	IMUsed()
	// 3xx Redirection
	MultipleChoices()
	MovedPermanently()
	Found()
	SeeOther()
	NotModified()
	UseProxy()
	TemporaryRedirect()
	PermanentRedirect()
	// 4xx Client Error
	BadRequest()
	Unauthorized()
	PaymentRequired()
	Forbidden()
	NotFound()
	MethodNotAllowed()
	NotAcceptable()
	ProxyAuthenticationRequired()
	RequestTimeout()
	Conflict()
	Gone()
	LengthRequired()
	PreconditionFailed()
	PayloadTooLarge()
	URITooLong()
	UnsupportedMediaType()
	RangeNotSatisfiable()
	ExpectationFailed()
	ImATeapot()
	MisdirectedRequest()
	UnprocessableEntity()
	Locked()
	FailedDependency()
	TooEarly()
	UpgradeRequired()
	PreconditionRequired()
	TooManyRequests()
	RequestHeaderFieldsTooLarge()
	UnavailableForLegalReasons()
	// 5xx Server Error
	InternalServerError()
	NotImplemented()
	BadGateway()
	ServiceUnavailable()
	GatewayTimeout()
	HTTPVersionNotSupported()
	VariantAlsoNegotiates()
	InsufficientStorage()
	LoopDetected()
	NotExtended()
	NetworkAuthenticationRequired()
}
